### ISSUE TITLE
Missing dependency: packaging

### ISSUE THREAD

**Issue by veghdev** [fugue-project/fugue-sql-antlr#20]
In `fugue_sql_antlr/parser.py` using `from packaging import version`
ModuleNotFoundError: No module named 'packaging'

I find that via fugue:
python3.10 -m venv ".venv"
source .venv/bin/activate
pip install ipyvizzu fugue[sql]

```python
import pandas as pd

import fugue.api as fa
import ipyvizzu.integrations.fugue

df = pd.DataFrame({"a": list("abcde"), "b": range(5)})
fa.fugue_sql_flow(
"""
    SELECT * FROM df WHERE b<5

    OUTPUT USING vizzu:bar(x="a",y="b")
""",
    df=df,
).run()
```

ImportError: No module named 'packaging'. Please try to install the package by `pip install fugue[sql]`.

**Comment by goodwanghan** [comment]
@veghdev my sincere apology for the big delay. And thanks a lot for the update. Will merge

**Comment by goodwanghan** [comment]
Actually it is not common to not have packaging package because it is a core package. And it may be because you didn't install python correctly. You can take a look at this thread: https://stackoverflow.com/questions/42222096/no-module-named-packaging

That being said I think it doesn't hurt to have it in the list. So I will release 0.1.8 to include it

**Comment by veghdev** [comment]
@goodwanghan thanks, but I don't find packaging in the [module index](https://docs.python.org/3.10/py-modindex.html#cap-p) nor in the [standard library](https://docs.python.org/3.10/library/index.html)
